### ISSUE TITLE
Support operations with string+bignumber and string+fraction

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#789]
Adding a string to a number or boolean works:

```js
math.add("2", 4)     // 6
math.add("2", true)  // 3
```

Whilst trying to add a string and a bignumber, fraction, or complex number fails:

```js
math.add("2", math.bignumber(4))    // TypeError: Unexpected type of argument in function add (expected: number, actual: BigNumber, index: 1)
math.add("2", math.fraction(2, 4))  // TypeError: Unexpected type of argument in function add (expected: number, actual: Fraction, index: 1)
math.add("2", math.complex(2, 0))   // TypeError: Unexpected type of argument in function add (expected: number, actual: Complex, index: 1)
```

Reason is that there are a few conversion definitions missing: string to bignumber, string to fraction, string to complex, and maybe a few more. [See code](https://github.com/josdejong/mathjs/blob/master/lib/core/typed.js#L66).

**Comment by Snorvarg** [comment]
Would it be easy for me to add your proposed fix on my local copy of math.js? If it works, I can upload the fix here, if that would help in any way.

**Comment by josdejong** [comment]
Should be fixed now in the `develop` branch, see this commit: https://github.com/josdejong/mathjs/commit/41f4cd6078f30df5760b7888abc8cca3d46ebd2c

Would be great if you could give it a try and see whether I didn't overlook anything.

**Comment by Snorvarg** [comment]
Works! This produces the answer 10: 

    vars = {a : 12, b : 3};
    ans = bigmath.eval('a/b + a/2', vars); 

Thank's a lot for the quick fix.

**Comment by josdejong** [comment]
:+1: I've just released v3.9.1 containing this fix.

**Comment by Snorvarg** [comment]
Is there a way to ask mathjs for it's version 'code-wise' ? 

I have mathjs installed in nodejs on a server, and installed it with npm. When I ask npm, it tells me version 3.9.1 is installed, but for some unknown reasons your fix don't seem to come through. 

...I was just thinking, if I can ask something like "math.version();" in my javascript-file, I would know for sure.

**Comment by ericman314** [comment]
math.version should work.

**Comment by Snorvarg** [comment]
Yep, that worked. But it says "3.9.0" even though I downloaded "3.9.1".

**Comment by josdejong** [comment]
I see I forgot to update the website, the latest version was only available on npm. Should be fixed now. 

Sorry for the inconvenience...

**Comment by josdejong** [comment]
Not sure though why this would happen when installing via npm

**Comment by Snorvarg** [comment]
When I installed it with npm, it now says "3.9.1", so npm is working fine. 

However, I have tricked myself; there seem to be some problems still. This example I gave you earlier are working:

```
var bigmath = math.create({
  number: 'BigNumber',  
  precision: 32
});

vars = {a : 12, b : 3};
ans = bigmath.eval('a/b + a/2', vars); 
```

But this, with bigger numbers, still produces the same error:

```
var bigmath = math.create({
  number: 'BigNumber',  
  precision: 32
});

vars = {a : 257, b : 936};
ans = bigmath.eval('a/b + a/2', vars); 
```

**Comment by josdejong** [comment]
You're touching a different issue now The error you get there is:
```
Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 0.2745726495726496). Use function bignumber(x) to convert to BigNumber
```

This error warns you that you're *thinking* you working with BigNumbers whilst you aren't: you're mixing numbers and BigNumbers which resulted in loss of precision. Reason is that in your expression the variables `a` and `b` are numbers, whilst the constant `2` is created as a BigNumber so a/b returns a number, a/2 returns a BigNumber, and adding a number to a BigNumber then trows this error.

I think the best solution is to convert your input variables `a` and `b` into BigNumbers first:

```js
var bigmath = math.create({
  number: 'BigNumber',  
  precision: 32
});

vars = {a : math.bignumber(257), b : math.bignumber(936)};
// or: 
// vars = {a : bigmath.eval('257'), b : bigmath.eval('936')};
ans = bigmath.eval('a/b + a/2', vars); 
```

Though there is a good reason for this, I realize that it works inconvenient. Let's think wether we can come up with a nicer solution to work in "BigNumber" mode.

**Comment by Snorvarg** [comment]
This works, and that's great. The only thing needed is a note about it in the documentation about BigNumbers, I don't believe there is.

http://mathjs.org/docs/datatypes/bignumbers.html

In there could be a simple example, why not the very example we have here? :)

```
var bigmath = math.create({
  number: 'BigNumber'
});

vars = {a : math.bignumber(257), b : math.bignumber(936)};

ans = bigmath.eval('a/b + a/2', vars); 
```
